name: Build and Test
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        target: [native]
        include:
          - os: ubuntu-latest
            target: x86_64-linux-musl
          - os: ubuntu-latest
            target: x86_64-linux-gnu
          - os: ubuntu-latest
            target: x86_64-macos
          - os: ubuntu-latest
            target: x86_64-windows
          - os: ubuntu-latest
            target: x86_64-freebsd
          - os: ubuntu-latest
            target: x86_64-netbsd
          - os: ubuntu-latest
            target: x86_64-openbsd
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: Setup Zig
        uses: mlugg/setup-zig@v2

      - name: Build
        run: zig build -Dtarget=${{ matrix.target }}
